version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: mlo-api-server
    ports:
      - "8082:8082"
    restart: on-failure
  redis:
    image: redis
    container_name: redis
    hostname: redis
    command: redis-server --requirepass $REDIS_PASSWORD --port 6379
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

