export const onionRecord: Record<number, string> = {
  0: 'empty',
  1: 'common',
  2: 'bully',
  3: 'gang',
  4: 'thief',
  5: 'mafia',
  6: 'complaint',
  7: 'joker',
  8: 'politician',
  9: 'president',
  10: 'student',
  11: 'developer',
  12: 'idol',
  13: 'princess',
  14: 'mom',
  15: 'dad',
  16: 'grandpa',
  17: 'grandma',
  18: 'worker',
  19: 'cartoon',
  20: 'mania',
  21: 'magician',
  22: 'fitness',
  23: 'medalist',
  24: 'trainer',
  25: 'negative',
  26: 'angry',
  27: 'devil',
  28: 'sad',
  29: 'patient',
  30: 'positive',
  31: 'clown',
  32: 'angel',
  33: 'gabriel',
};

export const onionNameRecord: Record<number, string> = {
  0: '양파가 없어요.',
  1: '기본 양파',
  2: '불량배 양파',
  3: '깡패 양파',
  4: '도둑 양파',
  5: '마피아 양파',
  6: '불만 양파',
  7: '조커 양파',
  8: '정치인 양파',
  9: '대통령 양파',
  10: '학생 양파',
  11: '개발자 양파',
  12: '아이돌 양파',
  13: '공주 양파',
  14: '엄마 양파',
  15: '아빠 양파',
  16: '할아버지 양파',
  17: '할머니 양파',
  18: '회사원 양파',
  19: '만화 양파',
  20: '매니아 양파',
  21: '마법사 양파',
  22: '운동 양파',
  23: '금메달 양파',
  24: '트레이너 양파',
  25: '부정적인 양파',
  26: '화난 양파',
  27: '악마 양파',
  28: '우울한 양파',
  29: '환자 양파',
  30: '긍정적인 양파',
  31: '광대 양파',
  32: '천사 양파',
  33: '대천사 양파',
};
